sudo: required
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=coverage
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=zpm
    - GCC_VERSION=6
global:
  env:
  - PROJECT=preproc
  - PROJECT_DIRECTORY=preproc
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- zpm run build-ci-library
after_success:
- zpm run deploy-ci-library
notifications:
  slack:
    secure: HDoqVm+fpuJHkbCcCys/UzqNDibt/iNgsWoKYIPR3SIuE6M9fxzGNrv6ZBBPhy4cmgSDUfOtmXTgsOk62/Hycjn9wrmkIsvERne472yEp35FgqExM5rAoIx3pqJhe5Y3j7GK/ioPe79PwUXTF+IHcUxNhcZdJpMwBMLCuEq/9wNqQHBBPkSL8ebsxHNZHFKgRUj1zHgM5a3kGDYfYhlA+dt6SGqAJJHMYRsC+UwwAg5bgpkcT8DlZmKzh4kUHxK3Aut+sJeWM0A6UX2MYvRa8paKlLuriMZzYJRNwkqnTCIVsBpo2hVrAyHv+qMuzowEUoEhDQzKiotfsLIBtSDNPHlYHSqa+VICZowMf9RAOxOdKAXLXAQ1u59sr+zfza6CEI8kcWZt2XxsxApmkhJFr8a6LlWHNIN6A3hmgn9FmxHILYKwfwNyyKG52dIc3ikN27tl8c6H38RtJdlbl8ZDrlbo+AUOt91WNWOoMX6C2ozoWdxxAb/TugTp3EglyHRA9i/6jW6ZrUP1Mlx3v+KkB01y4ps5jzvLJUbQRMFpejYL0Q3jnXWUm3fzs6j4x1qxs/TNx5SvHX1ipRkBDzL9czZAIhGpg7sZ1efygGotRLz85PwSToMdJQCWXCsyU2pgSr/Qe7dKrVAKSeO5VD4dqf83nz9tKIsfw+EjKkz8rjI=
